config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :lessons do
    resources :bookings do
      resources :reviews
    end
  end



  get '/bookings', to: 'bookings#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :student, class_name: 'User'
  belongs_to :lesson

  validates :date, presence: true
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  has_many :bookings
  has_many :reviews
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  validates :name, presence: true
  validates :price, presence: true, numericality: true
  validates :location, presence: true
  validates :description, presence: true

  include PgSearch::Model
  pg_search_scope :search_by_title_and_description,
    against: [:name, :description],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking

  validates :name, presence: true
  validates :comment, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings

  validates :role, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :role])

    # For additional in app/views/devise/registrations/edit.html.erb
    # devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
    @lesson = Lesson.find(params[:lesson_id])

    @booking.lesson = @lesson
  end

  def new
    @lesson = Lesson.find(params[:lesson_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @lesson = Lesson.find(params[:lesson_id])
    @booking.lesson = @lesson
    @booking.student = current_user

    if @booking.save
      redirect_to lesson_booking_path(@lesson, @booking)
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy

    redirect_to cocktail_path(@booking.lesson)
  end

  private

  def booking_params
    params.require(:booking).permit(:lesson_id, :date, :id)
  end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :set_lesson, only: [:show]

  def index
    if params[:query].present?
      sql_query = "name ILIKE :query OR description ILIKE :query"
      @lessons = Lesson.where(sql_query, query: "%#{params[:query]}%")
    else
      @lessons = Lesson.geocoded
    end
    @markers = @lessons.map do |lesson|
        {
          lat: lesson.latitude,
          lng: lesson.longitude,
          infoWindow: render_to_string(partial: "info_window", locals: {lesson: lesson})
        }
    end
  end

  def show
    @review = Review.new
    @booking = Booking.where(lesson: @lesson, student: current_user).last

    @markers = [{lat: @lesson.latitude, lng: @lesson.longitude}]
  end

  def create
    @lesson = Lesson.new(lesson_params)
      if @lesson.save
        redirect_to lesson_path(@lesson)
      else
        render 'lessons/new'
      end
  end

  def new
    @lesson = Lesson.new
  end

  private

  def set_lesson
    @lesson = Lesson.find(params[:id])
  end

  def lesson_params
    params.require(:lesson).permit(:name, :price, :description, :location, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end

  def show
    @lesson = Lesson.find(params[:lesson_id])
    @review = review.find(params[:id])
    @review.lesson = @review
  end

  def new
    @lesson = Lesson.find(params[:lesson_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @lesson = Lesson.find(params[:lesson_id])
    @booking = Booking.find(params[:booking_id])
    @review.booking = @booking

    if @review.save!
      redirect_to lesson_path(@lesson)
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :name, :stars, :lesson_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/destroy.html.erb
destroy.html.erb

app/views/bookings/index.html.erb
<div class = 'container'>
  <h1>YOUR BOOKED LESSONS</h1>


</div>


<% @bookings.each do |b| %>
<div class ="container col-6">
  <div class="card-product">
    <% if b.lesson.photo? %>
    <%= cl_image_tag b.lesson.photo, width:160, height:160 %>
    <% else %>
    <%= image_tag image_url("code3.jpg"), width:160, height:160 %>
    <% end %>
    <div class=" card-product-infos">
      <h2><%= b.lesson.name.capitalize %></h2>
      <p><%= b.date %>  </p>
      <p>Price:  <strong> <%= b.lesson.price %> € </strong></p>
    </div>
    <div class="card-body d-flex justify-content-end">
      <%= link_to 'View details', lesson_booking_path(b.lesson.id, b), class: "btn btn-primary newbutton  " %>
    </div>

  </div>
</div>
<% end %>

<!-- Footer -->

<!-- Footer -->

app/views/bookings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-6 offset-3">
      <div class="card_booking">
        <div class="card-body">
          <h1>MAKE A BOOKING</h1>

          <p>
            <%= simple_form_for [@lesson, @booking] do |f| %>
            <%= f.input :date%>
            <%= f.submit class: "btn btn-primary newbutton" %>
            <% end %>
          </p>
          <%= link_to 'Back to Lessons', lessons_path, class: "btn btn-outline-primary newbutton"  %>
          <div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container col-6 ">
  <h1>YOUR BOOKING</h1>
  <div class="card-product">
    <% if @lesson.photo? %>
    <%= cl_image_tag @lesson.photo, width:160, height:160 %>
    <% else %>
    <%= image_tag image_url("code3.jpg"), width:160, height:160 %>
    <% end %>

    <div class="card-header">
      Booking:
    </div>
    <div class=" card-product-infos">

      <h2><%= @booking.lesson.name.upcase %> </h2>
      <p>Date: <%= @booking.date %> </p>
      <p>Price: <strong><%= @booking.lesson.price %> €  </strong> </p>
    </div>

    <div class="card-body  d-flex justify-content-end">
      <a href="/bookings" class="card-link btn btn-outline-success newbutton ">Back to Bookings</a>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Tutorr</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v1.2.1/mapbox-gl.css' rel='stylesheet' />
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-lewagon">
      <%= link_to 'TUTORR', root_path, class: "navbar-brand"%>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarColor02">
        <ul class="navbar-nav mr-auto">
          <% if user_signed_in? %>

            <li class="nav-item active">
              <a class="nav-link" href="/lessons">Browse Lessons <span class="sr-only">(current)</span></a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="/bookings">Bookings</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/lessons/new">Add Lesson</a>

            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">About</a>
            </li>


            <li class="nav-item dropdown">
              <%= image_tag "guy.jpg", class: "avatar dropdown-toggle ", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <%= link_to "Action", "#", class: "dropdown-item" %>
                <%= link_to "Another action", "#", class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>

          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign-up", new_user_registration_path, class: "nav-link" %>
            </li>
        <% end %>
      </ul>


      </div>
    </nav>


    <%= yield %>

    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/lessons/_info_window.html.erb
<h4><%= lesson.name %></h4>
<p>Price:  <strong> <%= lesson.price %> € </strong></p>
<p><%= lesson.location %></p>

app/views/lessons/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0),rgba(0,0,0,0.1)), url(<%= asset_path 'background.jpg' %>);">
  <div class="container">
    <% if params[:query].present? %>
      <h1>Lessons for <strong><%= params[:query].upcase %></strong> </h1>
    <% else %>
      <h1>  Lessons</h1>
    <% end %>

  </div>
</div>

<!-- offset-2 -->

<div class ="container-fluid">
  <div class="row">
    <div class="col-8 offset-4 mb-4">
      <% if params[:query].present? %>
        <h4>FINDING RESULTS FOR: <%= params[:query].upcase %></h4>
      <% end %>
    </div>
  </div>

  <% if @lessons.count == 1 %>
    <h2> <%= @lessons.count  %> lesson available</h2>
  <%  elsif @lessons. count == 0 %>
  <h2> <%= %> </h2>
  <% else %>
    <h2> <%= @lessons.count  %> lessons available</h2>
  <% end %>

  <hr>

  <% if @lessons.any? %>
    <div class="row">
      <div class="col-lg-7">
        <% @lessons.each do |lesson| %>
          <div class="card-product">
            <% if lesson.photo? %>
              <%= cl_image_tag lesson.photo, width:160, height:160 %>
            <% else %>
              <%= image_tag image_url("code3.jpg"), width:160, height:160 %>
            <% end %>
            <div class="card-product-infos">
              <h2><%= lesson.name%></h2>
              <p><%= lesson.price %> €</p>
              <p><strong><%= lesson.location %></strong></p>
            </div>

            <div class="card-body d-flex justify-content-end">
             <%= link_to 'View details', lesson_path(lesson), class: "card-link btn btn-outline-success newbutton mr-3" %>
              <%= link_to 'Book now', new_lesson_booking_path(lesson), class: "btn btn-primary newbutton "%>
            </div>
          </div>

        <% end %>

        <div class="container d-flex justify-content-center">
          <%= link_to 'Back to homepage', root_path, class: "btn btn-outline-primary newbutton " %>
          </div>
      </div>

      <div class="col-lg-5">
        <div id="map" style="height: 100vh; position: -webkit-sticky; top: 0px" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= 'pk.eyJ1IjoiaWJtbWciLCJhIjoiY2szOGw0MWp1MDl2czNjcnRxZzJlZDB4diJ9.AcGFizvxSXA8jmm2hDFSKg' %>"></div>
      </div>
    </div>

  <% else %>
    <p class="center-p"> No lessons available! </p>
  <% end %>
</div>

app/views/lessons/new.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= asset_path 'background.jpg' %>);">
  <div class="container ">
    <h1>Create a lesson</h1>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-6 offset-3">
      <div class="card_new_lesson">
        <div class="card-body">
          <p class="mt-2">
            <%= simple_form_for [@lesson] do |l|%>
            <%= l.input :name%>
            <%= l.input :price%>
            <%= l.input :location%>
            <%= l.input :description%>
            <%= l.input :photo %>
            <%= l.input :photo_cache, as: :hidden %>
            <%= l.submit class: "btn btn-primary newbutton" %>
            <% end %>
          </p>
          <%= link_to 'Back to Lessons', lessons_path, class: "btn btn-outline-primary newbutton" %>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/lessons/show.html.erb
<div class="container col-lg-6 ">
  <h1>Lesson: <%= @lesson.name %> </h1>
  <div class="card-product">
    <% if @lesson.photo? %>
    <%= cl_image_tag @lesson.photo, width:160, height:160 %>
    <% else %>
    <%= image_tag image_url("code3.jpg"), width:160, height:160 %>
    <% end %>

    <div class=" card-product-infos">
      <h2> <%= @lesson.location %> </h2>
      <h2> <%= @lesson.price %> € </h2>

      <p> <%= @lesson.description%> </p>
    </div>
<!--       <video src="https://giphy.com/gifs/13UZisxBxkjPwI/html5"></video>
 -->    <div class="card-body  d-flex justify-content-end">
      <%= link_to 'Book now', new_lesson_booking_path(@lesson), class: "btn btn-outline-primary newbutton" %>
    </div>
  </div>

  <div class="card-map">
    <div id="map" style="height: 100vh; width: 100%; position: -webkit-sticky; top: 0px" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= 'pk.eyJ1IjoiaWJtbWciLCJhIjoiY2szOGw0MWp1MDl2czNjcnRxZzJlZDB4diJ9.AcGFizvxSXA8jmm2hDFSKg' %>"></div>
  </div>

  <%= link_to 'Back to Lessons', lessons_path, class: "card-link btn btn-outline-success newbutton-1 offset-4.5" %>

</div>



<div class="container">


    <div class="row">
      <div class="col-sm-7 offset-2">
        <hr/>
        <div class="review-block">
          <div class="row">
            <div class="col-sm-3">
              <div class="review-block-name"><a href="#">JOHNNY</a></div>
              <div class="review-block-date">November 21, 2019<br/>1 day ago</div>
            </div>
            <div class="col-sm-9">
              <div class="rate">
                <input type="radio" id="star5" name="rate" value="5" />
                <label for="star5" title="text">5 stars</label>
                <input type="radio" id="star4" name="rate" value="4" />
                <label for="star4" title="text">4 stars</label>
                <input type="radio" id="star3" name="rate" value="3" />
                <label for="star3" title="text">3 stars</label>
                <input type="radio" id="star2" name="rate" value="2" />
                <label for="star2" title="text">2 stars</label>
                <input type="radio" id="star1" name="rate" value="1" />
                <label for="star1" title="text">1 star</label>
              </div>
              <div class="review-block-title">Great lesson</div>
              <div class="review-block-description">I was completely amazed by the teaching style,the material I learned in just 2 hours! </div>
            </div>
          </div>
          <hr/>
          <div class="row">
            <div class="col-sm-3">
              <div class="review-block-name"><a href="#">BEN</a></div>
              <div class="review-block-date">November 8, 2019<br/>A few days ago</div>
            </div>
            <div class="col-sm-9">
              <div class="rate">
                <input type="radio" id="star5" name="rate" value="5" />
                <label for="star5" title="text">5 stars</label>
                <input type="radio" id="star4" name="rate" value="4" />
                <label for="star4" title="text">4 stars</label>
                <input type="radio" id="star3" name="rate" value="3" />
                <label for="star3" title="text">3 stars</label>
                <input type="radio" id="star2" name="rate" value="2" />
                <label for="star2" title="text">2 stars</label>
                <input type="radio" id="star1" name="rate" value="1" />
                <label for="star1" title="text">1 star</label>
              </div>
              <div class="review-block-title">Not my favorite</div>
              <div class="review-block-description">Although the teacher was good, I thought the material was not adequate</div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div> <!-- /container -->

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0),rgba(0,0,0,0.1)), url(<%= asset_path 'background.jpg' %>);">
  <div class="container col-8 text-align">
    <p>
      <span id="banner-typed-text"></span>
    </p>
    <div class="input-group md-form form-sm form-2 pl-0 ">


      <div class = "search-field">
        <%= form_tag lessons_path, method: :get do %>
        <%= text_field_tag :query, params[:query], class: "form-control my-0 py-1 red-border  ",
        placeholder: "Search for lessons"%>
      </div>
      <div class = "divalign">
        <%= button_tag( :class => "button-search divalign") do %>
        <i class="fas fa-search text-grey" aria-hidden="true"></i>
        <% end %>
      </div>
      <% end %>

    </div>
  </div>

</div>
<!-- Footer Links -->
<div class="container text-center1 text-md-left">

  <div class="row">
    <div class="col-md-3 col-lg-3 col-xl-3">
      <h6 class="text-uppercase mb-4 font-weight-bold">Social Networks</h6>
      <p>
        <div class="row">
          <div class="col-md-1"><i class="fab fa-facebook-f"></i></div>
          <div class="col-md-10">
            <a href="#" class="btn-floating btn-fb mx-1">
              Facebook
            </a>
          </div>
        </div>
      </p>
      <p>
        <div class="row">
          <div class="col-md-1"><i class="fab fa-twitter"></i></div>
          <div class="col-md-10">
            <a href="#" class="btn-floating btn-fb mx-1">
              Twitter
            </a>
          </div>
        </div>
      </p>
      <p>
        <div class="row">
          <div class="col-md-1"><i class="fab fa-linkedin-in"></i></div>
          <div class="col-md-10">
            <a href="#" class="btn-floating btn-fb mx-1">
              Linkedin
            </a>
          </div>
        </div>
      </p>
    </div>

    <hr class="w-100 clearfix d-md-none">

    <!-- Grid column -->
    <div class="col-md-3 col-lg-2 col-xl-3">
      <h6 class="text-uppercase mb-4 font-weight-bold">About us</h6>
      <p>
        <a href="#!">Who we are</a>
      </p>
      <p>
        <a href="#!">Blog</a>
      </p>
      <p>
        <a href="#!">Careers</a>
      </p>
    </div>
    <!-- Grid column -->

    <hr class="w-100 clearfix d-md-none">

    <!-- Grid column -->
    <div class="col-md-3 col-lg-2 col-xl-3">
      <h6 class="text-uppercase mb-4 font-weight-bold">Useful links</h6>
      <p>
        <a href="#!">Your Account</a>
      </p>
      <p>
        <a href="#!">Become an Affiliate</a>
      </p>
      <p>
        <a href="#!">Help</a>
      </p>
    </div>

    <!-- Grid column -->
    <hr class="w-100 clearfix d-md-none">

    <!-- Grid column -->
    <div class="col-md-3 col-lg-3 col-xl-3">
      <h6 class="text-uppercase mb-4 font-weight-bold">Contact</h6>
      <p>
        <i class="fas fa-home mr-3"></i>  Marques de Pombal, Lisbon
      </p>
      <p>
        <i class="fas fa-envelope mr-3"></i> tutorr-info@gmail.com
      </p>
      <p>
        <i class="fas fa-phone mr-3"></i> + 01 234 567 88
      </p>
      <p>
        <i class="fas fa-print mr-3"></i> + 01 234 567 89
      </p>
    </div>
  </div>
</div>


<!-- Footer -->
<div class="color1 ">
  <footer class="page-footer" >
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/"> tutorr.com</a>
    </div>
  </footer>
</div>
<!-- Footer -->